// Code generated by devtool; DO NOT EDIT.
package notioncodegen

// temporary import until they accept https://github.com/Masterminds/semver/pull/173
import "github.com/MarkRosemaker/semver"

var (
	// Version is the version of go-notion-codegen.
	Version = semver.MustParse("0.0.2")

	// GoVersion declares what version of Go should be used.
	GoVersion = semver.MustParse("1.18.3")
)
